Wait for the device ready after connecting the target
longhorn/go-spdk-helper pull request #15
Opened 2023-05-12 09:18 UTC by derekbit

2023-05-12 13:47 UTC, shuo-wu commented on pkg/nvme/initiator.go
> +	deviceGlob := fmt.Sprintf("/dev/disk/by-id/*%s*", i.UUID)
1. When and how can a new initiator get/load this UUID?
2. Is this necessary? I was thinking checking `/dev/nvmeXnY` is enough..

2023-05-12 16:09 UTC, derekbit commented on pkg/nvme/initiator.go
> +	deviceGlob := fmt.Sprintf("/dev/disk/by-id/*%s*", i.UUID)
Checking /dev/nvmeXnY is also fine.
OK, will check /dev/nvmeXnY instead.

2023-05-12 16:16 UTC, shuo-wu commented on pkg/nvme/initiator.go
> +	deviceGlob := fmt.Sprintf("/dev/disk/by-id/*%s*", i.UUID)
Then the remaining question is, how a new initiator can get/load this UUID.

2023-05-12 16:17 UTC, derekbit commented on pkg/nvme/initiator.go
> +	deviceGlob := fmt.Sprintf("/dev/disk/by-id/*%s*", i.UUID)
The UUID is the raid bdev's UUID.
If we check  /dev/nvmeXnY instead, we can remove the UUID input.

2023-05-12 16:18 UTC, shuo-wu commented on pkg/nvme/initiator.go
> +	deviceGlob := fmt.Sprintf("/dev/disk/by-id/*%s*", i.UUID)
We cannot get any info about RAID bdev here. It's out of a nvme initiator's capability. I think we can close this PR.

2023-05-12 16:21 UTC, derekbit commented on pkg/nvme/initiator.go
> +	deviceGlob := fmt.Sprintf("/dev/disk/by-id/*%s*", i.UUID)
`i.loadNVMeDeviceInfoWithoutLock()` only reads the device list rather than checks  `/dev/nvmeXnY` and retries, right? If yes, the check of  /dev/nvmeXnY is still necessary.

2023-05-12 16:23 UTC, shuo-wu commented on pkg/nvme/initiator.go
> +	deviceGlob := fmt.Sprintf("/dev/disk/by-id/*%s*", i.UUID)
It will get the major & minor numbers as well. But YES it does not retry.
You can add a retry instead.

2023-05-12 16:35 UTC, shuo-wu commented on pkg/nvme/initiator.go
> +	deviceGlob := fmt.Sprintf("/dev/disk/by-id/*%s*", i.UUID)
Can you:
1. Add `filepath.Glob(deviceGlob)` verification for `util.DetectDevice`
2. Directly use `util.DetectDevice` with a retry for [this part](https://github.com/longhorn/go-spdk-helper/blob/7af99589dd449a0241b1a3ece9b0254c9aa4ea17/pkg/nvme/initiator.go#L237-L244)

2023-05-12 16:41 UTC, derekbit commented on pkg/nvme/initiator.go
> +	deviceGlob := fmt.Sprintf("/dev/disk/by-id/*%s*", i.UUID)
> Add filepath.Glob(deviceGlob) verification for util.DetectDevice

What's the purpose of the verification?

2023-05-12 16:47 UTC, derekbit commented on pkg/nvme/initiator.go
> +	deviceGlob := fmt.Sprintf("/dev/disk/by-id/*%s*", i.UUID)
Check in `util.DetectDevice` is not helpful.

`ConnectTarget` -> `loadNVMeDeviceInfoWithoutLock` -> `GetDevices` -> `GetKnownDevices`
GetDevices errors out directly because `nvme list` gets nothing.

The check and retry should be between `ConnectTarget` and `loadNVMeDeviceInfoWithoutLock`.

2023-05-15 02:48 UTC, shuo-wu commented on pkg/nvme/initiator.go
> +	deviceGlob := fmt.Sprintf("/dev/disk/by-id/*%s*", i.UUID)
1. Can the retry be the like
```
for t := 0; t < int(timeout.Seconds()); t++ {
	if err = i.loadNVMeDeviceInfoWithoutLock(); err == nil {
		break
	}
	time.Sleep()
}
if err != nil {
	return errors.Wrapf(err, "failed to load device info after starting NVMe initiator %s", i.Name)
}
```
2. Function `loadNVMeDeviceInfoWithoutLock` will be used not only during the initiator start but also the initiator running state verification. That's why I prefer to add all kinds of device-related verification (`filepath.Glob(deviceGlob)`) into this function.
3. NIT: In function `loadNVMeDeviceInfoWithoutLock`, we already know the target device path `/dev/nvmeXnY`. I think we can directly use `DetectDevice` rather than `util.GetKnownDevices`

2023-05-15 04:12 UTC, derekbit commented on pkg/nvme/initiator.go
> +	deviceGlob := fmt.Sprintf("/dev/disk/by-id/*%s*", i.UUID)
Addressed. Thank you.

2023-05-15 04:16 UTC, shuo-wu submitted a review, later dismissed

2023-05-15 05:15 UTC, innobead requested changes
LGTM, but just one minor question.

2023-05-15 05:15 UTC, innobead commented on pkg/nvme/initiator.go
> +		}
You already use the glob to filter the device paths, so probably don't need to do another match here again?

2023-05-15 05:23 UTC, derekbit commented on pkg/nvme/initiator.go
> +		}
I'm thinking if no need to use glob.

2023-05-15 05:25 UTC, innobead commented on pkg/nvme/initiator.go
> +		}
feel the specific path should be good enough? Is there any possibility to have the prefix with the same namespace for different devices?

2023-05-15 05:29 UTC, derekbit commented on pkg/nvme/initiator.go
> +		}
I think no for now. WDYT? @shuo-wu

2023-05-15 08:23 UTC, shuo-wu commented on pkg/nvme/initiator.go
> +		}
No for now. Here I think for Longhorn the device name is always like `nvmeXn1`

2023-05-15 08:42 UTC, derekbit commented on pkg/nvme/initiator.go
> +		}
OK. Then, we can check the specific path here.

2023-05-15 12:26 UTC, derekbit commented on pkg/nvme/initiator.go
> +		}
Updated. Thank you.

2023-05-15 13:04 UTC, innobead approved these changes

2023-05-15 13:04 UTC, merged