Update BdevNvmeAttachController
longhorn/go-spdk-helper pull request #22
Opened 2023-05-21 05:48 UTC by derekbit

Add ctrlr-loss-timeout-sec, reconnect-delay-sec and fast-io-fail-timeout-sec for I/O error resiliency.

2023-05-21 12:57 UTC, innobead requested changes
LGTM, but one comment needed to resolve.

2023-05-21 12:57 UTC, innobead commented on pkg/spdk/client/basic.go
> +func (c *Client) BdevNvmeAttachController(name, subnqn, traddr, trsvcid string, trtype spdktypes.NvmeTransportType, adrfam spdktypes.NvmeAddressFamily, ctrlrLossTimeoutSec, reconnectDelaySec, fastIOF
Need to update the doc comment.

2023-05-21 13:06 UTC, derekbit commented on pkg/spdk/client/basic.go
> +func (c *Client) BdevNvmeAttachController(name, subnqn, traddr, trsvcid string, trtype spdktypes.NvmeTransportType, adrfam spdktypes.NvmeAddressFamily, ctrlrLossTimeoutSec, reconnectDelaySec, fastIOF
Updated. Thank you.

2023-05-21 15:37 UTC, innobead approved these changes

2023-05-21 15:37 UTC, merged

2023-05-22 04:10 UTC, shuo-wu commented on pkg/spdk/client/basic.go
> +			FastIOFailTimeoutSec: reconnectDelaySec,
typo here

2023-05-22 04:10 UTC, shuo-wu commented on app/cmd/basic/bdev_nvme.go
> +				Value: 0,
Do we need to apply default non-zero values for these timeouts?

2023-05-22 04:12 UTC, derekbit commented on app/cmd/basic/bdev_nvme.go
> +				Value: 0,
We can set some non-zero values.

2023-05-22 04:16 UTC, shuo-wu commented on app/cmd/basic/bdev_nvme.go
> +				Value: 0,
Sure. would you add and use some default non-zero values in this repo?

2023-05-22 04:19 UTC, derekbit commented on app/cmd/basic/bdev_nvme.go
> +				Value: 0,
Yes. Updated in https://github.com/longhorn/go-spdk-helper/pull/24/files.

2023-05-22 04:26 UTC, derekbit commented on pkg/spdk/client/basic.go
> +			FastIOFailTimeoutSec: reconnectDelaySec,
Fixed. Thank you.