Launch async message send and make the client thread-safe
longhorn/go-spdk-helper pull request #39
Opened 2023-06-14 14:20 UTC by shuo-wu

https://github.com/longhorn/longhorn/issues/6106

2023-06-16 06:18 UTC, derekbit commented on pkg/jsonrpc/client.go
> +}
`idCounter` uses lower 5 digits of current PID as the prefix. What's the purpose? Are there multiple processes creating clients?

2023-06-16 09:55 UTC, shuo-wu commented on pkg/jsonrpc/client.go
> +}
Previously YES. Then we need to get a unique number as the first ID value. 
Now the spdk engine service would use one client only but we cannot block users calling APIs with the binary. Hence I prefer to retain this.

2023-06-16 10:46 UTC, derekbit commented on pkg/jsonrpc/client.go
> +}
I see. 
> Previously YES. Then we need to get a unique number as the first ID value.

For the previous case, the PID of different clients in an engine service is same. Isn't it/

2023-06-16 16:09 UTC, shuo-wu commented on pkg/jsonrpc/client.go
> +}
Oh, YES. We need another way to pick up a unique init ID.

2023-06-16 23:56 UTC, derekbit commented on pkg/jsonrpc/client.go
> +}
Thanks for the clarification.

2023-08-15 10:59 UTC, derekbit commented on pkg/nvme/nvmecli.go
> +type CliDevice struct {
What does `Cli` mean?

2023-08-30 03:51 UTC, shuo-wu commented on pkg/nvme/nvmecli.go
> +type CliDevice struct {
`golint` will complain that there is no need to use prefix `Nvme` since the pkg name is `nvme`. Hence I have to use a different prefix here. `Cli` means Nvme Client/Initiator.

2023-08-30 03:52 UTC, shuo-wu commented on pkg/jsonrpc/client.go
>  		idCounter: rand.Uint32() % 10000,
prefix? Or you do mean the mod operation?

2023-09-13 08:25 UTC, derekbit commented on pkg/jsonrpc/client.go
>  		idCounter: rand.Uint32() % 10000,
Can you elaborate on the purpose of the idCounter? I don't remember the detail. Thank you.

2023-09-13 09:14 UTC, shuo-wu commented on pkg/jsonrpc/client.go
>  		idCounter: rand.Uint32() % 10000,
Each SPDK rpc request needs an id counter. If we start from `1`, there may be a conflict when there are multiple clients try to talk withe the tgt (the clients may be not created by longhorn-spdk-engine). Hence, we choose a random small number as the first id counter

2023-09-13 09:24 UTC, derekbit commented
In general, LGTM. Just two questions. 

https://github.com/longhorn/go-spdk-helper/pull/39#discussion_r1324161006
https://github.com/longhorn/go-spdk-helper/pull/39#discussion_r1324181957

2023-09-13 09:35 UTC, derekbit commented on pkg/jsonrpc/client.go
>  		idCounter: rand.Uint32() % 10000,
I see. Sounds reasonable. Is it possible that the users choose the same random number? What will happen in this case?

2023-09-13 09:41 UTC, shuo-wu commented on pkg/jsonrpc/client.go
>  	ticker := time.NewTicker(DefaultResponseReadWaitPeriod)
Without a ticker, this function will loop in `if !c.decoder.More() { continue }` billion times when there is no request for seconds. Is that OK?

2023-09-13 09:43 UTC, shuo-wu commented on pkg/jsonrpc/client.go
>  		idCounter: rand.Uint32() % 10000,
The official python binary typically uses `1` as the first counter. And YES, it's possible for the users to choose an identical number. Since it's not a main blocker or frequently happened case, I haven't taken too much time on raising a better solution.

2023-09-13 09:45 UTC, shuo-wu commented on pkg/jsonrpc/client.go
>  	ticker := time.NewTicker(DefaultResponseReadWaitPeriod)
Or if we directly use `if c.decoder.More() { do something }` in the `for` loop, we may not be able to handle a stop signal (`<-c.ctx.Done()`) when there is no request for a long time.

2023-09-13 11:47 UTC, derekbit commented on pkg/jsonrpc/client.go
>  		idCounter: rand.Uint32() % 10000,
Got it. Then, we can keep it as it is. Can you add a comment for the potential issue and future improvement? Thank you.

2023-09-13 11:48 UTC, derekbit commented on pkg/jsonrpc/client.go
>  	ticker := time.NewTicker(DefaultResponseReadWaitPeriod)
Understood. Then, I'm fine with the current implementation.

2023-09-13 12:33 UTC, shuo-wu commented on pkg/jsonrpc/client.go
>  		idCounter: rand.Uint32() % 10000,
Comment updated.

2023-09-13 13:33 UTC, derekbit submitted a review, later dismissed

2023-09-13 13:40 UTC, innobead commented
@shuo-wu the other PR just merged causing a new conflict. Please help resolve that. Thanks.

2023-09-14 02:50 UTC, shuo-wu commented
PR updated and conflict resolved.

2023-09-14 02:58 UTC, derekbit submitted a review, later dismissed

2023-09-14 03:18 UTC, innobead commented
for this, don't merge first. I would like to double check it later. thanks.

2023-10-02 03:15 UTC, innobead requested changes

2023-10-02 03:15 UTC, innobead commented on pkg/jsonrpc/client.go
> +	case c.msgWrapperQueue <- msgWrapper:
@shuo-wu as discussed, please ensure returning an error if the buffered queue is full to prevent the stuck operation. M
Need to check all queues used here%

After resolving this, we can merge this PR.

cc @derekbit

2023-11-14 08:53 UTC, shuo-wu commented on pkg/jsonrpc/client.go
> +	case c.msgWrapperQueue <- msgWrapper:
Checked and improved the flow for all queues:
1. For `msgWrapperQueue` and `respReceiverQueue`, there is always a timer during the signal sent.
2. For channels in `responseChans`, there is a single thread handling the signal sending and channel closing. It's impossible to encounter a queue congestion.

2023-11-14 13:18 UTC, innobead approved these changes
LGTM

2023-11-14 13:19 UTC, merged

2023-11-14 13:20 UTC, innobead commented on pkg/jsonrpc/client.go
> +	case c.msgWrapperQueue <- msgWrapper:
For 1, after checking the code, you probably don't need to use a timer for that, because you already use `select`, so the stuck situation should not happen. However, it's nice to have.