Fix the wrong timer for the json client response handling
longhorn/go-spdk-helper pull request #53
Opened 2023-12-05 03:24 UTC by shuo-wu

https://github.com/longhorn/longhorn/issues/7253

2023-12-07 15:32 UTC, innobead requested changes

2023-12-07 15:32 UTC, innobead commented on pkg/jsonrpc/client.go
> +			queueTimer := time.NewTimer(DefaultQueueBlockingTimeout)
Your original implementation is almost there, but what you missed seems to run into a special case below when using the reset call. It's required to handle differently (a little tedious). 

```go
// If a program has already received a value from t.C, the timer is known
// to have expired and the channel drained, so t.Reset can be used directly.
// If a program has not yet received a value from t.C, however,
// the timer must be stopped and—if Stop reports that the timer expired
// before being stopped—the channel explicitly drained:
//
//	if !t.Stop() {
//		<-t.C
//	}
//	t.Reset(d)
```

If this works, we can use this instead of repeatedly recreating the timer. Check first?

2023-12-08 02:41 UTC, shuo-wu commented on pkg/jsonrpc/client.go
> +			queueTimer := time.NewTimer(DefaultQueueBlockingTimeout)
Wait... Doesn't `t.Stop()` mean trying to expire the timer (rather than checking if the timer is expired or not)? Then `t.Reset(d)` must be invalid...

The comment about `t.Stop()`:
// It returns true if the call stops the timer, false if the timer has already
// expired or been stopped.

2023-12-08 11:03 UTC, innobead commented on pkg/jsonrpc/client.go
> +			queueTimer := time.NewTimer(DefaultQueueBlockingTimeout)
From the doc, it will try to stop the timer but can't prevent any read from the channel of the timer. That said, the design doesn't handle the channel cleanup part. Thus, you need to secure there is no data still in the channel after resetting, or the next timer timeout would be incorrect.

This is why there are some discussions about not recommending the use of Reset due to it's confusing behavior. 

> // Stop prevents the Timer from firing.
// It returns true if the call stops the timer, false if the timer has already
// expired or been stopped.
//
// Stop does not close the channel, to prevent a read from the channel succeeding
// incorrectly.

2023-12-08 11:04 UTC, innobead commented on pkg/jsonrpc/client.go
> +			queueTimer := time.NewTimer(DefaultQueueBlockingTimeout)
We can merge this PR first, but you could figure out this later.

2023-12-08 11:04 UTC, innobead approved these changes

2023-12-08 11:04 UTC, merged

2023-12-12 03:29 UTC, shuo-wu commented on pkg/jsonrpc/client.go
> +			queueTimer := time.NewTimer(DefaultQueueBlockingTimeout)
I see. And I tested this part. It works as well. Here is the new PR: https://github.com/longhorn/go-spdk-helper/pull/54