Add a linear dm device on the top of a nvme device
longhorn/go-spdk-helper pull request #55
Opened 2023-12-17 16:08 UTC by derekbit

https://github.com/longhorn/longhorn/issues/7357

2023-12-18 13:37 UTC, innobead requested changes
In general, LGTM. Just a few comments need to resolve.

Besides, there are two things we can improve later.
- Add unit tests if needed, especially for string parsing related. Technically, we can just add tests for exported methods/functions; however, some previate ones could deserve a simple test as well. This can help us ensure the expected result.
- Add doc comments for any public methods, even though they are straightforward from naming.

2023-12-18 13:37 UTC, innobead commented on pkg/nvme/initiator.go
> +		defer lock.Unlock()
This lock section repeats in other methods of this struct. I would suggest creating another method for it to reuse instead.

2023-12-18 13:37 UTC, innobead commented on pkg/nvme/initiator.go
> +		return err
Wrap the error, then return.

2023-12-19 02:10 UTC, derekbit commented on pkg/nvme/initiator.go
> +		defer lock.Unlock()
It looks a clear and standard pattern of a lock: create lock, acquire lock and release lock. Wrapping it might become not straightforward. I prefer to keep the pattern as it is. WDYT? @innobead

2023-12-19 02:10 UTC, derekbit commented on pkg/nvme/initiator.go
> +			i.logger.WithError(err).Errorf("Failed to start NVMe initiator %s", i.Name)
Updated. Thank you.

2023-12-19 08:49 UTC, derekbit commented
> In general, LGTM. Just a few comments need to resolve.
> 
> Besides, there are two things we can improve later.
> 
> * Add unit tests if needed, especially for string parsing related. Technically, we can just add tests for exported methods/functions; however, some previate ones could deserve a simple test as well. This can help us ensure the expected result.

I will add unit tests for nvme and device mapper in another PR.

> * Add doc comments for any public methods, even though they are straightforward from naming.

2023-12-19 09:24 UTC, derekbit commented on pkg/util/dmsetup.go
> +	_, err := executor.Execute(dmsetupBinary, opts)
Handled in https://github.com/longhorn/go-spdk-helper/pull/56

2023-12-19 09:38 UTC, innobead commented on pkg/nvme/initiator.go
> +		defer lock.Unlock()
My previous comment was wrong, because the defer part won't work after moving to a reusable method.

P.S. hope golang have macro mechanism :)

2023-12-19 09:39 UTC, innobead approved these changes

2023-12-19 09:39 UTC, merged