Replace executor with the implementation in go-commit-libs
longhorn/go-spdk-helper pull request #56
Opened 2023-12-19 09:22 UTC by derekbit

Longhorn/longhorn#7357

2023-12-19 11:00 UTC, innobead requested changes
In general, LGTM. Just one comment.

2023-12-19 11:00 UTC, innobead commented on app/cmd/nvmecli/nvmecli.go
> +	namespaces := []typeslib.Namespace{typeslib.NamespaceMnt, typeslib.NamespaceIpc, typeslib.NamespaceNet}
it: this variable can be a reusable constant, as we always use these three namespaces.

2023-12-20 06:44 UTC, c3y1huang commented on app/cmd/spdktgt/spdktgt.go
> +	return target.StartTarget(c.String("spdk-dir"), c.StringSlice("opts"), ne.Execute)
It seems that `util.Execute` was executing commands within the current namespace, which should be achievable with [NewExecutor](https://github.com/longhorn/go-common-libs/blob/main/exec/exec.go#L25). Any reason for opting for `NewNamespaceExecutor`, which involves switching namespaces?

2023-12-20 06:44 UTC, c3y1huang commented on pkg/nvme/initiator.go
> +	executor, err := nslib.NewNamespaceExecutor(typeslib.ProcessNone, typeslib.ProcDirectory, namespaces)
Same here, if I'm understanding correctly, `util.GetExecutorByHostProc("")` was performing local execution. Is there any reason for opting namespace switch?

2023-12-20 09:27 UTC, derekbit commented on app/cmd/spdktgt/spdktgt.go
> +	return target.StartTarget(c.String("spdk-dir"), c.StringSlice("opts"), ne.Execute)
> Any reason for opting for NewNamespaceExecutor, which involves switching namespaces?

The interfaces are mismatching.

> It seems that util.Execute was executing commands within the current namespace, which should be achievable with [NewExecutor](https://github.com/longhorn/go-common-libs/blob/main/exec/exec.go#L25).

I've checked the two namespaced executors and run

- `nsenter --mount=/host/proc/1... --...`
- `nsenter --mount=/proc/1/.... --...`

Frome the results, the first one is executed in in the host namespace, and the second one is in the pod namespace.
It seems the second one is equivalent to NewExecutor.

2023-12-20 09:30 UTC, derekbit commented on pkg/nvme/initiator.go
> +	executor, err := nslib.NewNamespaceExecutor(typeslib.ProcessNone, typeslib.ProcDirectory, namespaces)
Explaned in https://github.com/longhorn/go-spdk-helper/pull/56#discussion_r1432466999.
I would like to make the interface clean and work for different namespaces.

2023-12-20 11:53 UTC, derekbit commented on app/cmd/nvmecli/nvmecli.go
> +	typeslib "github.com/longhorn/go-common-libs/types"
Addressed. Thank you.

2023-12-20 11:53 UTC, derekbit commented on app/cmd/nvmecli/nvmecli.go
> +	namespaces := []typeslib.Namespace{typeslib.NamespaceMnt, typeslib.NamespaceIpc, typeslib.NamespaceNet}
Addressed. Thank you.

2023-12-20 13:29 UTC, innobead commented on app/cmd/nvmecli/nvmecli.go
> +	namespaces := []typeslib.Namespace{typeslib.NamespaceMnt, typeslib.NamespaceIpc, typeslib.NamespaceNet}
@c3y1huang as I commented in another thread, please have this into common-libs as well.

2023-12-20 14:33 UTC, innobead commented on app/cmd/spdktgt/spdktgt.go
> +	return target.StartTarget(c.String("spdk-dir"), c.StringSlice("opts"), ne.Execute)
Since PID 1 in the IM pod is a privileged pod, we are able to see all processes there.

2023-12-20 14:34 UTC, innobead approved these changes

2023-12-20 14:34 UTC, merged