Update jsonrpc ResponseError
longhorn/go-spdk-helper pull request #8
Opened 2023-05-07 14:17 UTC by shuo-wu

2023-05-07 17:07 UTC, innobead requested changes
LGTM. Just one minior code sugar suggested.

One question about `StopExposeBdev`. Why we speicially created a target (via NvmfCreateTransport) even though if there are no targets found and required to stop? 

```go
unc (c *Client) StopExposeBdev(nqn string) error {
	nvmfTransportList, err := c.NvmfGetTransports(spdktypes.NvmeTransportTypeTCP, "")
	if err != nil && !jsonrpc.IsJsonRPCRespErrorNoSuchDevice(err) {
		return err
	}
	if len(nvmfTransportList) == 0 {
		if _, err := c.NvmfCreateTransport(spdktypes.NvmeTransportTypeTCP); err != nil {
			return err
		}
	}
```

2023-05-07 17:07 UTC, innobead commented on pkg/jsonrpc/types.go
> +	return false
Can be.

```go
	return jsonRPCError.Code == RespErrorCodeNoSuchDevice && jsonRPCError.Message != RespErrorMsgNoSuchDevice

```

2023-05-08 02:57 UTC, shuo-wu commented
> One question about StopExposeBdev. Why we speicially created a target (via NvmfCreateTransport) even though if there are no targets found and required to stop?

I don't remember the detail but it may be related to the check I just added (The missing of the transport may lead to the following APIs return NoSuchDevice errors). I think we can remove this create now.

2023-05-08 03:15 UTC, innobead approved these changes
LGTM

2023-05-08 03:15 UTC, merged